src/gerobak/apps/profile/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from gerobak.apps.profile import views

urlpatterns = patterns('',
    (r'^(?P<pid>[a-f0-9]{8})/install/(?P<task_id>[\w\d\-]+)/$',
        views.install_result),
    (r'^(?P<pid>[a-f0-9]{8})/install/$', views.install),

    (r'^(?P<pid>[a-f0-9]{8})/upgrade/(?P<task_id>[\w\d\-]+)/$',
        views.upgrade_result),
    (r'^(?P<pid>[a-f0-9]{8})/upgrade/$', views.upgrade),
    (r'^(?P<pid>[a-f0-9]{8})/dist-upgrade/$', views.dist_upgrade),

    (r'^(?P<pid>[a-f0-9]{8})/search/(?P<task_id>[\w\d\-]+)/$',
        views.search_result),
    (r'^(?P<pid>[a-f0-9]{8})/search/$', views.search),

    (r'^(?P<pid>[a-f0-9]{8})/update/$', views.update),
    (r'^(?P<pid>[a-f0-9]{8})/sources/$', views.sources),
    (r'^(?P<pid>[a-f0-9]{8})/status/$', views.status),
    (r'^(?P<pid>[a-f0-9]{8})/show/(?P<pkg>[a-z0-9.-]+)/$', views.info),
    #(r'^(?P<pid>\d+)/sources/', include(gerobak.apps.source.urls)),
    (r'^(?P<pid>[a-f0-9]{8})/$', views.show),
    (r'^$', views.index),
)

src/gerobak/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

import gerobak.apps.profile.urls
#import gerobak.apps.queue

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT}),

    (r'^admin/', include(admin.site.urls)),

    (r'^doc/howto/$', 'django.views.generic.simple.direct_to_template', 
        {'template': 'doc/howto.html'}),

    (r'^p/', include(gerobak.apps.profile.urls)),
    #(r'^q/', include(gerobak.apps.queue.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^task/', include('celery.urls')),
    (r'^$', 'gerobak.views.index'),
)

src/gerobak/apps/profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save

from gerobak import utils

class Profile(models.Model):
    pid = models.CharField(max_length=8)

    user = models.ForeignKey(User)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=250, null=True, blank=True)

    arch = models.CharField(max_length=10, choices=settings.GEROBAK_ARCHS,
                            default=settings.GEROBAK_DEFAULT_ARCH)

    repo_updated = models.DateTimeField(null=True, default=None)

    sources_updated = models.DateTimeField(null=True, default=None)
    sources_total = models.IntegerField(null=True, default=None)

    status_updated = models.DateTimeField(null=True, default=None)
    status_hash = models.CharField(max_length=32, null=True, default=None)
    status_size = models.IntegerField(default=0)

    tid_update = models.CharField(max_length=36, null=True, default=None)

    def is_ready(self):
        return self.repo_updated is not None and \
               self.status_updated is not None

    def generate_pid(self):
        import uuid
        return str(uuid.uuid4()).split('-')[0]

src/gerobak/apps/profile/views.py
from datetime import datetime
import tempfile
import os

try:
    import simplejson as json
except ImportError:
    import json

from django.http import HttpResponse, Http404, HttpResponseForbidden
from django import forms
from django.conf import settings
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

from celery.result import AsyncResult

from gerobak import utils, apt
from gerobak.apps.profile import tasks
from gerobak.apps.profile.models import Profile
from gerobak.apps.profile.utils import parse_apt_install, \
                                       parse_apt_search, \
                                       parse_apt_show

class AddProfileForm(forms.Form):
    name = forms.CharField(max_length=50)
    desc = forms.CharField(max_length=250, label="Description")
    arch = forms.ChoiceField(choices=settings.GEROBAK_ARCHS,
                             initial=settings.GEROBAK_DEFAULT_ARCH,
                             label="Architecture")

class UploadStatusForm(forms.Form):
    file = forms.FileField()

class SourcesForm(forms.Form):
    sources = forms.CharField(widget=forms.Textarea)

class InstallForm(forms.Form):
    packages = forms.CharField()

class SearchForm(forms.Form):
    packages = forms.CharField()

def _post(func):
    def _func(request, pid, *args, **kwargs):
        if request.method != 'POST':
            return redirect(show, pid)
        return func(request, pid, *args, **kwargs)
    return _func

def _profile(func):
    def _func(request, pid, *args, **kwargs):
        profile = get_object_or_404(Profile, pid=pid)
        if profile.user != request.user:
            # TODO
            return HttpResponseForbidden()
        return func(request, profile, *args, **kwargs)
    return _func

def _updated(func):
    def _func(request, profile, *args, **kwargs):
        if profile.status_updated is None or \
           profile.sources_updated is None or \
           profile.repo_updated is None:
            
            request.user.message_set.create(message="update needed.")
            return redirect(show, profile.pid)

        return func(request, profile, *args, **kwargs)
    return _func

def _pre_updated(func):
    def _func(request, profile, *args, **kwargs):
        if profile.status_updated is None or \
           profile.sources_updated is None:
            
            request.user.message_set.create(message="status or sources is missing")
            return redirect(show, profile.pid)

        return func(request, profile, *args, **kwargs)
    return _func

def _decompress(realname, path):
    # FIXME uncompressed file size should be checked and limited

    fid, tmp = tempfile.mkstemp()
    fo = open(tmp, 'w')

    if realname.endswith('.gz'):
        import gzip
        fi = gzip.open(path, 'rb')

    elif realname.endswith('.bz2'):
        import bz2
        fi = bz2.BZ2File(path, 'r')

    fo.write(fi.read())

    fi.close()
    fo.close()

    return tmp

def handle_uploaded_status(profile, file):
    # FIXME file size should be checked and limited

    path = utils.get_path(profile.pid)
    status = file.temporary_file_path()

    tmp = None
    if file.name.endswith('.gz') or file.name.endswith('.bz2'):
        tmp = _decompress(file.name, file.temporary_file_path())
        utils.update_status(path, tmp)
        os.unlink(tmp)

    else:
        utils.update_status(path, status)

    return path

def _upgrade(request, profile, type='upgrade'):
    task = tasks.upgrade.delay(profile.id, type)
    data = {'stat': 'ok',
            'task_id': task.task_id}

    return render_to_response('profile/json', {'json': json.dumps(data)},
                              mimetype='text/plain')

@login_required
@_post
@_profile
@_updated
def upgrade(request, profile):
    return _upgrade(request, profile)

@login_required
@_post
@_profile
@_updated
def dist_upgrade(request, profile):
    return _upgrade(request, profile, 'dist-upgrade')

@login_required
@_profile
@_updated
def upgrade_result(request, profile, task_id):
    task = AsyncResult(task_id)
    if task.status == 'SUCCESS':
        type, ret, out, err = task.result
        return _show_install(ret, out, err, 'json', type=type)
    elif task.status == 'PENDING':
        data = {'stat': 'pending'}
    else:
        data = {'stat': 'fail'}
    return render_to_response('profile/json', {'json': json.dumps(data)},
                              mimetype='text/plain')

def _show_install(ret, out, err, format, **kwargs):
    if ret != 0:
        txt = err
    else:
        txt = out

    extra, suggested, recommended, install, packages, newest, \
        upgrade, keptback, errors = parse_apt_install(txt)

    type = kwargs.get('type', 'install');
    pkgs = kwargs.get('packages', []);

    if format == 'html':
        return render_to_response('profile/install.html',
                                  {'packages': pkgs,
                                   'extra': extra,
                                   'suggested': suggested,
                                   'recommended': recommended,
                                   'install': install,
                                   'urls': packages,
                                   'newest': newest,
                                   'upgrade': upgrade,
                                   'keptback': keptback,
                                   'errors': errors})
    elif format == 'json':
        data = {'stat': 'ok',
                'type': type,
                'data': {'packages': pkgs,
                         'extra': extra,
                         'suggested': suggested,
                         'recommended': recommended,
                         'install': install,
                         'urls': packages,
                         'newest': newest,
                         'upgrade': upgrade,
                         'keptback': keptback,
                         'errors': errors}}
        jdata = json.dumps(data)
        return render_to_response('profile/json', {'json': jdata},
                                  mimetype='text/plain')

@login_required
@_post
@_profile
@_updated
def install(request, profile):
    format = request.GET.get('format', 'html')
    if not format in ['html', 'json']:
        format = 'html'

    form = InstallForm(request.POST)
    if form.is_valid():
        packages = form.cleaned_data['packages']
        task = tasks.install.delay(profile.id, packages)

        data = {'stat': 'ok',
                'task_id': task.task_id}
        return render_to_response('profile/json', {'json': json.dumps(data)},
                                  mimetype='text/plain')
    else:
        print "invalid"
        print form.as_p()
    return HttpResponse('install pid=%d' % profile.pid)

@login_required
@_profile
@_updated
def install_result(request, profile, task_id):
    task = AsyncResult(task_id)
    if task.status == 'SUCCESS':
        pkgs, ret, out, err = task.result
        return _show_install(ret, out, err, 'json', packages=pkgs)
    elif task.status == 'PENDING':
        data = {'stat': 'pending'}
    else:
        data = {'stat': 'fail'}
    return render_to_response('profile/json', {'json': json.dumps(data)},
                              mimetype='text/plain')

@login_required
@_profile
@_updated
def info(request, profile, pkg):
    format = request.GET.get('format', 'html')
    if not format in ['html', 'json']:
        format = 'html'

    path = utils.get_path(profile.pid)
    pkg, code, out, err = apt.show(path, pkg)

    if code == 100: # Not found
        raise Http404()
        
    info, keys = parse_apt_show(out)

    if info is None:
        pkg = None
        sdesc = ''
        desc = ''
        data = []
    else:
        sdesc = info['Description'].split("\n")[0]
        desc = "\n".join(info['Description'].split("\n")[1:])

        data = []
        for key in keys:
            data.append((key, info[key]))

    if format == 'html':
        return render_to_response('profile/info.html',
                                  {'pkg': pkg,
                                   'desc': desc,
                                   'sdesc': sdesc,
                                   'data': data})

    elif format == 'json':
        data = {'stat': 'ok',
                'type': 'pkgshow',
                'data': {'package': pkg,
                         'desc': desc,
                         'sdesc': sdesc,
                         'data': data}}
        jdata = json.dumps(data)
        return render_to_response('profile/json', {'json': jdata},
                                  mimetype='application/json')

@login_required
@_profile
@_updated
def search(request, profile):
    format = request.GET.get('format', 'html')
    if not format in ['html', 'json']:
        format = 'html'

    form = SearchForm(request.POST)
    if form.is_valid():
        packages = form.cleaned_data['packages']
        task = tasks.search.delay(profile.id, packages)

        data = {'stat': 'ok',
                'task_id': task.task_id}
        return render_to_response('profile/json', {'json': json.dumps(data)},
                                  mimetype='text/plain')
    else:
        print "invalid"
        print form.as_p()
    return HttpResponse('search pid=%d' % profile.pid)

@login_required
@_profile
@_updated
def search_result(request, profile, task_id):
    task = AsyncResult(task_id)
    if task.status == 'SUCCESS':
        pkgs, ret, out, err = task.result
        pkgs = ' '.join(pkgs)

        return render_to_response('profile/search.json',
                                  {'pkgs': pkgs,
                                   'ret': ret,
                                   'items': parse_apt_search(out)})
    elif task.status == 'PENDING':
        data = {'stat': 'pending'}
    else:
        data = {'stat': 'fail'}

src/gerobak/templates/profile/base.html
{% extends "base.html" %}

<script type="text/javascript" src="/media/gerobak.js"></script>
<script type="text/javascript" src="/media/jquery.js"></script>

{% block content %}
<div class="profile">
{% block profilecontent %}{% endblock %}
</div>
{% endblock %}

src/gerobak/templates/profile/index.html
{% extends "profile/base.html" %}

{% block profilecontent %}

<h2>Profiles</h2>

{% if profiles %}

<table class="profiles">
<tr><th>Name</th><th>Architecture</th><th>Description</th></tr>
{% for profile in profiles %}
<tr><td><a href="{% url gerobak.apps.profile.views.show profile.pid %}">{{ profile.name }}</a></td>
    <td>{{ profile.arch }}</td>
    <td>{{ profile.desc }}</td>
</tr>
{% endfor %}
</table>

{% else %}

<p>You have to add a profile first!</p>
<p>A profile represents a machine. Use a separate profile for each machine you
have.</p>

{% endif %}

<div class="add">
<h3>Add New Profile</h3>
<form method="post">
{{ form.as_p }}
<p><input type="submit" value="Add Profile"/></p>
</form>
</div>

{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="/media/profile-index.css"/>
{% if not profiles %}
<script type="text/javascript">
$(document).ready(function() {
    $('#id_name').focus();
});
</script>
{% endif %}
{% endblock %}

src/gerobak/templates/profile/info.html
<h1>{{ pkg }}</h1>
<p>{{ sdesc }}</p>
<pre>{{ desc }}</pre>
<table>
{% for k, v in data %}
{% ifnotequal k "Description" %}
<tr><td>{{ k }}</td><td>{{ v }}</td></tr>
{% endifnotequal %}
{% endfor %}
</table>

src/gerobak/templates/profile/install.html
Status code: {{ ret }} <br/>

Packages: {{ pkgs }} <br/>

output

<pre>{{ out }}</pre>

error

<pre>{{ err }}</pre>

src/gerobak/templates/profile/search.html
Status code: {{ ret }} <br/>

Packages: {{ pkgs }} <br/>

output

<pre>{{ out }}</pre>

error

<pre>{{ err }}</pre>

src/gerobak/templates/profile/show.html
{% extends "profile/base.html" %}

{% block profilecontent %}

{% if messages %}
<div class="msg ui-widget"><div class="ui-state-error ui-corner-all">
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
</div></div>
{% endif %}

<div class="title">
<h2>{{ profile.name }}</h2>
{% if profile.desc %}
<p>&ndash; {{ profile.desc }}</p>
{% endif %}
</div>

<div class="tabs">
    <ul>
    <li><a href="#settings">Status</a></li>
    {% if profile.repo_updated %}
    <li><a href="#search">Search</a></li>
    <li><a href="#install">Install</a></li>
    <li><a href="#upgrade">Upgrade</a></li>
    {% endif %}
    </ul>
    <div id="settings">

        <div id="status" class="block">
            <h3>Status File</h3>
            <div>
            {% if profile.status_updated %}
            <p><span class="label">Last update:</span> {{ profile.status_updated|date:"j M y H:i" }}</p>
            {% else %}
            <p><span class="label">Last update:</span> Never</p>
            {% endif %}
            <p><span class="label">Size:</span> {{ profile.status_size|default_if_none:"Unknown" }}</p>
            <p><span class="label">MD5 Hash:</span> <code class="md5">{{ profile.status_hash|default_if_none:"Unknown" }}</code></p>
            <p class="cmd"><span onclick="show_dialog('#dialog-status-upload')">upload status file</span>
                <!--
                <span onclick="show_dialog('#dialog-status-predefined')">use prefedined status file</span>
                -->
            </p>
            </div>
        </div>
        
        <div id="sources" class="block">
            <h3>Software Sources</h3>
            <div>
            {% if profile.sources_updated %}
            <p><span class="label">Last update:</span> {{ profile.sources_updated|date:"j M y H:i" }}</p>
            {% else %}
            <p><span class="label">Last update:</span> Never</p>
            {% endif %}
            <p><span class="label">Total:</span> {{ profile.sources_total|default_if_none:"0" }}</p>
            <p class="cmd"><span onclick="show_dialog('#dialog-sources')">view/edit sources</span></p>
            </div>
        </div>
        
        <div id="update" class="block">
            <h3>Update Repository</h3>
            <div>
            {% if profile.repo_updated %}
            <p><span class="label">Last update:</span> {{ profile.repo_updated|date:"j M y H:i" }}</p>
            {% else %}
            <p><span class="label">Last update:</span> Never</p>
            {% endif %}
            <form method="post" action="update/" onsubmit="profile.update.start(); return false;">
            {% if profile.tid_update %}
            <p class="cmd"><input type="submit" value="Update Repository" disabled="disabled"/></p>
            {% else %}
            <p class="cmd"><input type="submit" value="Update Repository"/></p>
            {% endif %}
            </form>
            </div>
        </div>

    </div>
    {% if profile.repo_updated %}
    <div id="search">
        <form method="post" action="search/" onsubmit="profile.search.start(this); return false;">
        <p><label for="id_packages">Keyword:</label>
            {{ search.packages }}
            <input type="submit" value="search"/>
        </p>
        </form>
        <div id="search-result"></div>
    </div>
    <div id="install">
        <form onsubmit="profile.install.add_form(); return false;">
        <div><label>Add package:</label> 
            <div><input type="text" id="install-package-add"/> 
            <input type="submit" value="add"/> 
            <input type="button" value="clear" onclick="profile.install.clear()"/>
            </div>
        </div>
        </form>
        <div id="install-package-list"><p>Packages: </p><ul></ul></div>
        <div id="install-package-button"><input type="button" value="install" onclick="profile.install.start()"/></div>
        <div id="install-result"></div>
    </div>
    <div id="upgrade">
        <form method="post" action="upgrade/" onsubmit="profile.upgrade.start(); return false;">
        <input type="submit" value="upgrade"/>
        </form>
        
        <form method="post" action="dist-upgrade/" onsubmit="profile.dist_upgrade.start(); return false;">
        <input type="submit" value="dist-upgrade"/>
        </form>
        <div id="upgrade-result"></div>
    </div>
    {% endif %}
</div>

<div class="dialog" id="dialog-status-upload" title="Upload Status File">
<p>This file is located at <code>/var/lib/dpkg/status</code> in your
machine.</p> 
<p>You can also upload the 
    gzip (<code>.gz</code>) or bzip2 (<code>.bz2</code>) 
    compressed version of the file.</p>
<form method="post" action="status/" enctype="multipart/form-data" onsubmit="profile.status.start(this);">
{{ upload.as_p }}
<p><input type="submit" value="Upload"/></p>
</form>
</div>

<div class="dialog" id="dialog-status-predefined" title="Use Predefined Status File">
predefined status file
</div>

<div class="dialog" id="dialog-sources" title="Software Sources">
<p>Write your sources list as written in <code>/etc/apt/sources.list</code></p>
<form method="post" action="sources/">
{{ sources.sources }}
<p><input type="submit" value="Update"/></p>
</form>
</div>

<div class="dialog" id="dialog-package-show" title="Package Information">
</div>

{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="/media/profile.css"/>
<script type="text/javascript" src="/media/zeroclipboard/ZeroClipboard.js"></script>
<script type="text/javascript" src="/media/profile.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    profile.init();
    {% if profile.tid_update %}
    profile.update.check('{{ profile.tid_update }}');
    {% endif %}
    ZeroClipboard.setMoviePath('/media/zeroclipboard/ZeroClipboard.swf');
});
</script>
{% endblock %}

src/gerobak/templates/profile/update.html
Status code: {{ ret }} <br/>

output

<pre>{{ out }}</pre>

error

<pre>{{ err }}</pre>